"use client";

import { useForm, type Resolver } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { employeeSchema, type EmployeeFormValues } from "@/schemas/employee.schema";
import { useDynamicFields } from "@/hooks/useDynamicFields";
import { CanAccess } from "@/components/shared/Guards";
import { Button } from "@/components/ui/Button";
import { Field, Input, Select } from "@/components/ui/Input";

interface EmployeeFormProps {
  defaultValues?: Partial<EmployeeFormValues>;
  onSubmit: (values: EmployeeFormValues) => void;
  isLoading?: boolean;
}

export function EmployeeForm({ defaultValues, onSubmit, isLoading }: EmployeeFormProps) {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<EmployeeFormValues>({
    resolver: zodResolver(employeeSchema) as unknown as Resolver<EmployeeFormValues>,
    defaultValues: {
      role: "sales_executive",
      employmentStatus: "active",
      ...defaultValues,
    },
  });

  const { data: departments } = useDynamicFields("department");
  const { data: banks } = useDynamicFields("bank_name");

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      {/* Personal Information */}
      <fieldset className="rounded-xl border border-neutral-200/80 p-4 bg-white shadow-2xs space-y-4">
        <legend className="px-2 text-xs font-bold uppercase tracking-wider text-neutral-500">Personal Information</legend>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Full Name" required error={errors.fullName?.message}>
            <Input invalid={!!errors.fullName} {...register("fullName")} />
          </Field>
          <Field label="Email" required error={errors.email?.message}>
            <Input type="email" invalid={!!errors.email} {...register("email")} />
          </Field>
          <Field label="Phone" error={errors.phone?.message}>
            <Input {...register("phone")} />
          </Field>
        </div>
        {/* Employee ID is auto-generated by the backend on creation. */}
      </fieldset>

      {/* Employment Details */}
      <fieldset className="rounded-xl border border-neutral-200/80 p-4 bg-white shadow-2xs space-y-4">
        <legend className="px-2 text-xs font-bold uppercase tracking-wider text-neutral-500">Employment Details</legend>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Role" required error={errors.role?.message}>
            <Select {...register("role")} defaultValue={defaultValues?.role ?? "sales_executive"}>
              <option value="master">Master Admin</option>
              <option value="hr_manager">HR Manager</option>
              <option value="sales_manager">Sales Manager</option>
              <option value="sales_executive">Sales Executive</option>
            </Select>
          </Field>
          <Field label="Department" error={errors.department?.message}>
            <Select {...register("department")} defaultValue={defaultValues?.department ?? ""}>
              <option value="">Select department</option>
              {departments?.map((d) => <option key={d.id} value={d.value}>{d.value}</option>)}
            </Select>
          </Field>
          {/* Designation is automatically derived from the selected Role. */}
          <Field label="Joining Date" error={errors.joiningDate?.message}>
            <Input type="date" {...register("joiningDate")} />
          </Field>
          <CanAccess module="hrms" page="employees" action="deactivate">
            <Field label="Employment Status" error={errors.employmentStatus?.message}>
              <Select {...register("employmentStatus")} defaultValue={defaultValues?.employmentStatus ?? "active"}>
                <option value="active">Active</option>
                <option value="probation">Probation</option>
                <option value="on_notice">On Notice</option>
                <option value="resigned">Resigned</option>
                <option value="terminated">Terminated</option>
              </Select>
            </Field>
          </CanAccess>
        </div>
      </fieldset>

      {/* Salary & Bank */}
      <fieldset className="rounded-xl border border-neutral-200/80 p-4 bg-white shadow-2xs space-y-4">
        <legend className="px-2 text-xs font-bold uppercase tracking-wider text-neutral-500">Salary &amp; Bank Details</legend>
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Basic Salary (AED)" error={errors.basicSalary?.message}>
            <Input type="number" step="0.01" {...register("basicSalary")} />
          </Field>
          <Field label="Allowances (AED)" error={errors.allowances?.message}>
            <Input type="number" step="0.01" {...register("allowances")} />
          </Field>
          <Field label="Bank Name" error={errors.bankName?.message}>
            <Select {...register("bankName")} defaultValue={defaultValues?.bankName ?? ""}>
              <option value="">Select bank</option>
              {banks?.map((b) => <option key={b.id} value={b.value}>{b.value}</option>)}
            </Select>
          </Field>
          <Field label="Bank Account Number" error={errors.bankAccountNumber?.message}>
            <Input {...register("bankAccountNumber")} />
          </Field>
        </div>
      </fieldset>

      <div className="flex justify-end pt-2">
        <Button type="submit" loading={isLoading}>
          Save Employee
        </Button>
      </div>
    </form>
  );
}
